const KEY='mtyd_balloon_quotes_v1', SETTINGS='mtyd_balloon_settings_v1';
const defaults={business:'Me To You Designs',phone:'',email:'',web:'',rate:25,profit:20,overhead:5,mileage:.45,deposit:25,terms:'Quotes are valid for 7 days unless otherwise stated. A deposit is required to secure the booking. Personalised balloon work cannot be returned or refunded once production has started. Final colours and details are agreed before making.'};
let settings=JSON.parse(localStorage.getItem(SETTINGS)||'null')||defaults; let quotes=JSON.parse(localStorage.getItem(KEY)||'[]');
const $=id=>document.getElementById(id), money=n=>'£'+Number(n||0).toFixed(2), save=()=>localStorage.setItem(KEY,JSON.stringify(quotes)), saveS=()=>localStorage.setItem(SETTINGS,JSON.stringify(settings));
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));$(page).classList.add('active-page');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={dashboard:'Balloon Quote Calculator',quick:'Quick Quote',detailed:'Detailed Quote',helium:'Helium Calculator',quotes:'Saved Quotes',settings:'Settings'};$('pageTitle').textContent=titles[page];window.scrollTo({top:0,behavior:'smooth'});if(page==='quotes')renderQuotes();updateStats()}
document.querySelectorAll('.nav,[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page||b.dataset.go)));$('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');$('newQuote').onclick=()=>go('quick');
function updateStats(){ $('statQuotes').textContent=quotes.length; const m=new Date().getMonth(), y=new Date().getFullYear(); $('statMonth').textContent=money(quotes.filter(q=>{let d=new Date(q.created);return d.getMonth()===m&&d.getFullYear()===y}).reduce((a,q)=>a+q.total,0)); $('statOutstanding').textContent=money(quotes.reduce((a,q)=>a+Math.max(0,q.total-(q.deposit||0)),0)); $('statRate').textContent=money(settings.rate)+'/hr'; renderRecent() }
function renderRecent(){const box=$('recentQuotes');const arr=quotes.slice(0,5);box.innerHTML=arr.length?arr.map(row).join(''):'<div class="form-card"><p style="color:#786c72">No quotes yet. Create your first one above.</p></div>';bindQuoteButtons(box)}
function row(q){return `<div class="quote-row"><div><div class="name">${esc(q.customer||'Unnamed customer')}</div><small>${esc(q.ref)} · ${esc(q.event||q.type||'Balloon design')} · ${q.status||'Draft'}</small></div><strong>${money(q.total)}</strong><div class="quote-actions"><button class="icon-btn" data-view="${q.id}">View</button><button class="icon-btn" data-print="${q.id}">Print</button><button class="icon-btn" data-delete="${q.id}">Delete</button></div></div>`}
function bindQuoteButtons(box){box.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showQuote(b.dataset.view));box.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>printQuote(b.dataset.print));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this quote?')){quotes=quotes.filter(q=>q.id!==b.dataset.delete);save();renderQuotes();updateStats();toast('Quote deleted')}})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function calcQuick(){const mat=+$('qMaterials').value||0, lab=(+$('qMinutes').value||0)/60*settings.rate, over=settings.overhead, del=(+$('qMiles').value||0)*settings.mileage, extra=+$('qExtras').value||0, sub=mat+lab+over+del+extra, profit=sub*settings.profit/100,total=sub+profit;[['qMatOut',mat],['qLabOut',lab],['qOverOut',over+extra],['qDelOut',del],['qProfitOut',profit],['qTotalOut',total]].forEach(([i,v])=>$(i).textContent=money(v));return {mat,lab,over:over+extra,del,profit,total}}
['qMaterials','qMinutes','qMiles','qExtras'].forEach(i=>$(i).addEventListener('input',calcQuick));calcQuick();
function makeRef(){return 'MTYD-'+new Date().getFullYear()+'-'+Math.random().toString(36).slice(2,8).toUpperCase()}
function addQuote(data){const q={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),ref:makeRef(),created:new Date().toISOString(),deposit:data.total*settings.deposit/100,balance:data.total*(1-settings.deposit/100),status:'Draft',...data};quotes.unshift(q);save();updateStats();return q}
$('saveQuick').onclick=()=>{const c=calcQuick();if(!$('qCustomer').value.trim()){toast('Add a customer name first');return}const q=addQuote({customer:$('qCustomer').value,event:$('qEvent').value,type:$('qType').value,date:$('qDate').value,description:$('qDesc').value,total:c.total,breakdown:c,items:[]});toast('Quote saved');showQuote(q.id)};
let items=[];function renderItems(){const box=$('items');box.innerHTML=items.map((x,i)=>`<div class="item-row"><input data-i="${i}" class="iname" value="${esc(x.name)}" placeholder="e.g. 11\" latex balloons"><input data-i="${i}" class="iqty" type="number" value="${x.qty}" min="0"><input data-i="${i}" class="icost" type="number" value="${x.cost}" min="0" step="0.01"><div class="item-sub">${money(x.qty*x.cost)}</div><button class="icon-btn remove" data-i="${i}">×</button></div>`).join('');box.querySelectorAll('input').forEach(el=>el.oninput=()=>{const i=+el.dataset.i;if(el.classList.contains('iname'))items[i].name=el.value;if(el.classList.contains('iqty'))items[i].qty=+el.value||0;if(el.classList.contains('icost'))items[i].cost=+el.value||0;calcDetailed();renderItems()});box.querySelectorAll('.remove').forEach(b=>b.onclick=()=>{items.splice(+b.dataset.i,1);renderItems();calcDetailed()});}
$('addItem').onclick=()=>{items.push({name:'',qty:1,cost:0});renderItems()};function calcDetailed(){const mat=items.reduce((a,x)=>a+(x.qty*x.cost),0),lab=(+$('dMinutes').value||0)/60*(+$('dRate').value||settings.rate),over=+$('dOver').value||0,del=(+$('dMiles').value||0)*settings.mileage,sub=mat+lab+over+del,profit=sub*settings.profit/100,total=sub+profit;[['dMatOut',mat],['dLabOut',lab],['dOverOut',over],['dDelOut',del],['dProfitOut',profit],['dTotalOut',total]].forEach(([i,v])=>$(i).textContent=money(v));return {mat,lab,over,del,profit,total}}
$('dRate').value=settings.rate;['dMinutes','dRate','dMiles','dOver'].forEach(i=>$(i).addEventListener('input',calcDetailed));items=[{name:'',qty:1,cost:0}];renderItems();calcDetailed();
$('saveDetailed').onclick=()=>{const c=calcDetailed();if(!$('dCustomer').value.trim()){toast('Add a customer name first');return}const q=addQuote({customer:$('dCustomer').value,event:$('dEvent').value,type:$('dType').value,date:$('dDate').value,description:$('dDesc').value,total:c.total,breakdown:c,items:items.filter(x=>x.name)});toast('Detailed quote saved');showQuote(q.id)};
function helium(){const p=+$('hPrice').value||0,cap=+$('hCapacity').value||0,v=+$('hVolume').value||0,n=+$('hCount').value||1,per=cap? p*(v/cap):0;$('hPer').textContent=money(per);$('hTotal').textContent='Total helium cost: '+money(per*n)}['hPrice','hCapacity','hVolume','hCount'].forEach(i=>$(i).addEventListener('input',helium));helium();
function renderQuotes(){const search=($('searchQuotes').value||'').toLowerCase(),filter=$('filterQuotes').value;const arr=quotes.filter(q=>(filter==='all'||q.status===filter)&&[q.customer,q.ref,q.event,q.type].join(' ').toLowerCase().includes(search));$('allQuotes').innerHTML=arr.length?arr.map(row).join(''):'<div class="form-card"><p style="color:#786c72">No matching quotes.</p></div>';bindQuoteButtons($('allQuotes'))}$('searchQuotes').oninput=renderQuotes;$('filterQuotes').onchange=renderQuotes;
function showQuote(id){const q=quotes.find(x=>x.id===id);if(!q)return;$('modalContent').innerHTML=`<div class="quote-paper"><header><div><span class="eyebrow">${esc(settings.business)}</span><h2>QUOTE</h2></div><div><b>${esc(q.ref)}</b><small>${new Date(q.created).toLocaleDateString('en-GB')}</small></div></header><p><b>Prepared for</b><br>${esc(q.customer)}</p><p><b>Event</b><br>${esc(q.event||'')} ${q.date?'· '+new Date(q.date+'T00:00').toLocaleDateString('en-GB'):''}</p><p><b>Design</b><br>${esc(q.type||'')}</p><p>${esc(q.description||'')}</p>${q.items?.length?'<hr><b>Included</b><ul>'+q.items.map(x=>`<li>${esc(x.qty)} × ${esc(x.name)}</li>`).join('')+'</ul>':''}<div class="quote-total">Total ${money(q.total)}</div><p>Deposit: ${money(q.deposit)}<br>Balance: ${money(q.balance)}</p><hr><small>${esc(settings.terms)}</small></div><div class="actions"><button class="secondary" onclick="closeModal()">Close</button><button class="primary" onclick="printQuote('${q.id}')">Print / Save PDF</button></div>`;$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
function printQuote(id){const q=quotes.find(x=>x.id===id);if(!q)return;const w=window.open('','_blank');w.document.write(`<html><head><title>${esc(q.ref)} — ${esc(settings.business)}</title><style>body{font-family:Arial,sans-serif;padding:50px;color:#30252a}header{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding-bottom:20px}h1{font-family:Georgia,serif;color:#a95f78}h2{font-family:Georgia,serif}.total{font-size:28px;color:#a95f78;text-align:right;font-weight:700;margin:30px 0}small{line-height:1.6}</style></head><body><header><div><div>${esc(settings.business)}</div><h1>QUOTE</h1></div><div><b>${esc(q.ref)}</b><br>${new Date(q.created).toLocaleDateString('en-GB')}</div></header><h2>Prepared for</h2><p>${esc(q.customer)}</p><h2>Event</h2><p>${esc(q.event||'')} ${q.date?'— '+new Date(q.date+'T00:00').toLocaleDateString('en-GB'):''}</p><h2>Design</h2><p>${esc(q.type||'')}</p><p>${esc(q.description||'')}</p>${q.items?.length?'<h2>Included</h2><ul>'+q.items.map(x=>`<li>${esc(x.qty)} × ${esc(x.name)}</li>`).join('')+'</ul>':''}<div class="total">Total ${money(q.total)}</div><p>Deposit: ${money(q.deposit)}<br>Balance: ${money(q.balance)}</p><hr><small>${esc(settings.terms)}</small><script>window.print()<\/script></body></html>`);w.document.close()}
function loadSettings(){[['sBusiness','business'],['sPhone','phone'],['sEmail','email'],['sWeb','web'],['sRate','rate'],['sProfit','profit'],['sOverhead','overhead'],['sMileage','mileage'],['sDeposit','deposit'],['sTerms','terms']].forEach(([i,k])=>$(i).value=settings[k])}loadSettings();$('saveSettings').onclick=()=>{[['sBusiness','business'],['sPhone','phone'],['sEmail','email'],['sWeb','web'],['sRate','rate'],['sProfit','profit'],['sOverhead','overhead'],['sMileage','mileage'],['sDeposit','deposit'],['sTerms','terms']].forEach(([i,k])=>settings[k]=['rate','profit','overhead','mileage','deposit'].includes(k)?+$ (i).value||0:$(i).value);saveS();$('dRate').value=settings.rate;calcQuick();calcDetailed();updateStats();toast('Settings saved')};
updateStats();
